In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
np.linspace(-3,3,num=100)

array([-3.        , -2.93939394, -2.87878788, -2.81818182, -2.75757576,
       -2.6969697 , -2.63636364, -2.57575758, -2.51515152, -2.45454545,
       -2.39393939, -2.33333333, -2.27272727, -2.21212121, -2.15151515,
       -2.09090909, -2.03030303, -1.96969697, -1.90909091, -1.84848485,
       -1.78787879, -1.72727273, -1.66666667, -1.60606061, -1.54545455,
       -1.48484848, -1.42424242, -1.36363636, -1.3030303 , -1.24242424,
       -1.18181818, -1.12121212, -1.06060606, -1.        , -0.93939394,
       -0.87878788, -0.81818182, -0.75757576, -0.6969697 , -0.63636364,
       -0.57575758, -0.51515152, -0.45454545, -0.39393939, -0.33333333,
       -0.27272727, -0.21212121, -0.15151515, -0.09090909, -0.03030303,
        0.03030303,  0.09090909,  0.15151515,  0.21212121,  0.27272727,
        0.33333333,  0.39393939,  0.45454545,  0.51515152,  0.57575758,
        0.63636364,  0.6969697 ,  0.75757576,  0.81818182,  0.87878788,
        0.93939394,  1.        ,  1.06060606,  1.12121212,  1.18

In [3]:
np.random.randint(50,101, size=50)

array([ 51,  60,  82,  58,  59,  85,  88,  50,  67,  69,  98,  56,  69,
        96,  59, 100,  71,  96,  86,  98,  68,  85,  83,  86,  65,  83,
        64,  69,  56,  68,  76,  54,  79,  97,  80,  85,  73,  63,  94,
        81,  54,  79,  50,  79,  64,  95,  77,  85,  67,  52])

In [8]:
data1=np.random.randint(50,101, size=(50,5))
print(data1)
data1 + 5

[[ 74  55  65  55  85]
 [ 89  51  59  63  62]
 [ 95  78  73  92  85]
 [ 64  77  78  63  95]
 [ 92  55  80  72  62]
 [ 95  86  87  68  96]
 [ 66  73  50  75  63]
 [ 67  57  52  56  95]
 [ 59  75  71  98  81]
 [ 64  70  54  77  63]
 [ 83  58  95  59  81]
 [ 50  59  86  89  75]
 [ 54  68  93  83  52]
 [ 60  66  80  86  84]
 [ 67  60  71  62  84]
 [ 89  63  81  51  70]
 [ 50  97  74  71  90]
 [ 91  60  61  61  70]
 [ 94  79  77  81  78]
 [ 54  75  51  89  84]
 [ 51  97  57  97  66]
 [ 61  58  79  71  63]
 [ 76  83  72  58  93]
 [ 57  99  93  52  92]
 [ 99  94  96  95  85]
 [ 53  98  77  92  57]
 [ 75  66  61  74  95]
 [ 67  54  98  96  64]
 [ 87  70  94  50  58]
 [ 65  95  70  51  75]
 [ 70  52  89  59  81]
 [ 60  97  74  79  97]
 [ 99  62  87  56  53]
 [ 51  64  82  62  64]
 [ 64  54  71  71  77]
 [ 94  88  81  83  63]
 [ 91 100  56  92  95]
 [ 57  92  74  54  87]
 [ 99  75  54  82  63]
 [ 56  53  81  81  73]
 [ 91  90  89  87  58]
 [ 81  52  72  87  70]
 [ 65  89  87  64  50]
 [ 68  90  

array([[ 79,  60,  70,  60,  90],
       [ 94,  56,  64,  68,  67],
       [100,  83,  78,  97,  90],
       [ 69,  82,  83,  68, 100],
       [ 97,  60,  85,  77,  67],
       [100,  91,  92,  73, 101],
       [ 71,  78,  55,  80,  68],
       [ 72,  62,  57,  61, 100],
       [ 64,  80,  76, 103,  86],
       [ 69,  75,  59,  82,  68],
       [ 88,  63, 100,  64,  86],
       [ 55,  64,  91,  94,  80],
       [ 59,  73,  98,  88,  57],
       [ 65,  71,  85,  91,  89],
       [ 72,  65,  76,  67,  89],
       [ 94,  68,  86,  56,  75],
       [ 55, 102,  79,  76,  95],
       [ 96,  65,  66,  66,  75],
       [ 99,  84,  82,  86,  83],
       [ 59,  80,  56,  94,  89],
       [ 56, 102,  62, 102,  71],
       [ 66,  63,  84,  76,  68],
       [ 81,  88,  77,  63,  98],
       [ 62, 104,  98,  57,  97],
       [104,  99, 101, 100,  90],
       [ 58, 103,  82,  97,  62],
       [ 80,  71,  66,  79, 100],
       [ 72,  59, 103, 101,  69],
       [ 92,  75,  99,  55,  63],
       [ 70, 1

In [13]:
import pandas as pd
df1 = pd.DataFrame(data=data1,index=range(50),columns=['國文','英文','數學','物理','化學'])

In [16]:
sum1 = df1['國文']+df1['英文']+df1['物理']+df1['數學']+df1['化學']
print(sum1)

0     334
1     324
2     423
3     377
4     361
5     432
6     327
7     327
8     384
9     328
10    376
11    359
12    350
13    376
14    344
15    354
16    382
17    343
18    409
19    353
20    368
21    332
22    382
23    393
24    469
25    377
26    371
27    379
28    359
29    356
30    351
31    407
32    357
33    323
34    337
35    409
36    434
37    364
38    373
39    344
40    415
41    362
42    355
43    418
44    330
45    434
46    384
47    379
48    412
49    296
dtype: int64
