In [1]:
import numpy as np
np.linspace(-3,3)

array([-3.        , -2.87755102, -2.75510204, -2.63265306, -2.51020408,
       -2.3877551 , -2.26530612, -2.14285714, -2.02040816, -1.89795918,
       -1.7755102 , -1.65306122, -1.53061224, -1.40816327, -1.28571429,
       -1.16326531, -1.04081633, -0.91836735, -0.79591837, -0.67346939,
       -0.55102041, -0.42857143, -0.30612245, -0.18367347, -0.06122449,
        0.06122449,  0.18367347,  0.30612245,  0.42857143,  0.55102041,
        0.67346939,  0.79591837,  0.91836735,  1.04081633,  1.16326531,
        1.28571429,  1.40816327,  1.53061224,  1.65306122,  1.7755102 ,
        1.89795918,  2.02040816,  2.14285714,  2.26530612,  2.3877551 ,
        2.51020408,  2.63265306,  2.75510204,  2.87755102,  3.        ])

In [2]:
np.linspace(-3,3,num=100)

array([-3.        , -2.93939394, -2.87878788, -2.81818182, -2.75757576,
       -2.6969697 , -2.63636364, -2.57575758, -2.51515152, -2.45454545,
       -2.39393939, -2.33333333, -2.27272727, -2.21212121, -2.15151515,
       -2.09090909, -2.03030303, -1.96969697, -1.90909091, -1.84848485,
       -1.78787879, -1.72727273, -1.66666667, -1.60606061, -1.54545455,
       -1.48484848, -1.42424242, -1.36363636, -1.3030303 , -1.24242424,
       -1.18181818, -1.12121212, -1.06060606, -1.        , -0.93939394,
       -0.87878788, -0.81818182, -0.75757576, -0.6969697 , -0.63636364,
       -0.57575758, -0.51515152, -0.45454545, -0.39393939, -0.33333333,
       -0.27272727, -0.21212121, -0.15151515, -0.09090909, -0.03030303,
        0.03030303,  0.09090909,  0.15151515,  0.21212121,  0.27272727,
        0.33333333,  0.39393939,  0.45454545,  0.51515152,  0.57575758,
        0.63636364,  0.6969697 ,  0.75757576,  0.81818182,  0.87878788,
        0.93939394,  1.        ,  1.06060606,  1.12121212,  1.18

In [3]:
np.random.randint(50,101, size=50)

array([ 51,  60,  82,  58,  59,  85,  88,  50,  67,  69,  98,  56,  69,
        96,  59, 100,  71,  96,  86,  98,  68,  85,  83,  86,  65,  83,
        64,  69,  56,  68,  76,  54,  79,  97,  80,  85,  73,  63,  94,
        81,  54,  79,  50,  79,  64,  95,  77,  85,  67,  52])

In [8]:
data1=np.random.randint(50,101, size=(50,5))
print(data1)
data1 + 5

[[ 74  55  65  55  85]
 [ 89  51  59  63  62]
 [ 95  78  73  92  85]
 [ 64  77  78  63  95]
 [ 92  55  80  72  62]
 [ 95  86  87  68  96]
 [ 66  73  50  75  63]
 [ 67  57  52  56  95]
 [ 59  75  71  98  81]
 [ 64  70  54  77  63]
 [ 83  58  95  59  81]
 [ 50  59  86  89  75]
 [ 54  68  93  83  52]
 [ 60  66  80  86  84]
 [ 67  60  71  62  84]
 [ 89  63  81  51  70]
 [ 50  97  74  71  90]
 [ 91  60  61  61  70]
 [ 94  79  77  81  78]
 [ 54  75  51  89  84]
 [ 51  97  57  97  66]
 [ 61  58  79  71  63]
 [ 76  83  72  58  93]
 [ 57  99  93  52  92]
 [ 99  94  96  95  85]
 [ 53  98  77  92  57]
 [ 75  66  61  74  95]
 [ 67  54  98  96  64]
 [ 87  70  94  50  58]
 [ 65  95  70  51  75]
 [ 70  52  89  59  81]
 [ 60  97  74  79  97]
 [ 99  62  87  56  53]
 [ 51  64  82  62  64]
 [ 64  54  71  71  77]
 [ 94  88  81  83  63]
 [ 91 100  56  92  95]
 [ 57  92  74  54  87]
 [ 99  75  54  82  63]
 [ 56  53  81  81  73]
 [ 91  90  89  87  58]
 [ 81  52  72  87  70]
 [ 65  89  87  64  50]
 [ 68  90  

array([[ 79,  60,  70,  60,  90],
       [ 94,  56,  64,  68,  67],
       [100,  83,  78,  97,  90],
       [ 69,  82,  83,  68, 100],
       [ 97,  60,  85,  77,  67],
       [100,  91,  92,  73, 101],
       [ 71,  78,  55,  80,  68],
       [ 72,  62,  57,  61, 100],
       [ 64,  80,  76, 103,  86],
       [ 69,  75,  59,  82,  68],
       [ 88,  63, 100,  64,  86],
       [ 55,  64,  91,  94,  80],
       [ 59,  73,  98,  88,  57],
       [ 65,  71,  85,  91,  89],
       [ 72,  65,  76,  67,  89],
       [ 94,  68,  86,  56,  75],
       [ 55, 102,  79,  76,  95],
       [ 96,  65,  66,  66,  75],
       [ 99,  84,  82,  86,  83],
       [ 59,  80,  56,  94,  89],
       [ 56, 102,  62, 102,  71],
       [ 66,  63,  84,  76,  68],
       [ 81,  88,  77,  63,  98],
       [ 62, 104,  98,  57,  97],
       [104,  99, 101, 100,  90],
       [ 58, 103,  82,  97,  62],
       [ 80,  71,  66,  79, 100],
       [ 72,  59, 103, 101,  69],
       [ 92,  75,  99,  55,  63],
       [ 70, 1

In [30]:
import pandas as pd
df1 = pd.DataFrame(data=data1,index=[f"第{i}號"for i in range(1,51)],columns=['國文','英文','數學','物理','化學'])
df1

國文   英文  數學  物理  化學
第1號    74   55  65  55  85
第2號    89   51  59  63  62
第3號    95   78  73  92  85
第4號    64   77  78  63  95
第5號    92   55  80  72  62
第6號    95   86  87  68  96
第7號    66   73  50  75  63
第8號    67   57  52  56  95
第9號    59   75  71  98  81
第10號   64   70  54  77  63
第11號   83   58  95  59  81
第12號   50   59  86  89  75
第13號   54   68  93  83  52
第14號   60   66  80  86  84
第15號   67   60  71  62  84
第16號   89   63  81  51  70
第17號   50   97  74  71  90
第18號   91   60  61  61  70
第19號   94   79  77  81  78
第20號   54   75  51  89  84
第21號   51   97  57  97  66
第22號   61   58  79  71  63
第23號   76   83  72  58  93
第24號   57   99  93  52  92
第25號   99   94  96  95  85
第26號   53   98  77  92  57
第27號   75   66  61  74  95
第28號   67   54  98  96  64
第29號   87   70  94  50  58
第30號   65   95  70  51  75
第31號   70   52  89  59  81
第32號   60   97  74  79  97
第33號   99   62  87  56  53
第34號   51   64  82  62  64
第35號   64   54  71  71  77
第36號   94   88  81  83  63
第37號   91  100  56  92  95
第38號   57   92  74  54  87
第39號   99   75  54  82  63
第40號   56   53  81  81  73
第41號   91   90  89  87  58
第42號   81   52  72  87  70
第43號   65   89  87  64  50
第44號   68   90  82  98  80
第45號   91   59  76  53  51
第46號  100   61  96  94  83
第47號   77   69  97  83  58
第48號   64   78  90  82  65
第49號   94   99  81  80  58
第50號   52   67  67  53  57

In [20]:
df1.loc['第10號':'第15號']

國文  英文  數學  物理  化學
第10號  64  70  54  77  63
第11號  83  58  95  59  81
第12號  50  59  86  89  75
第13號  54  68  93  83  52
第14號  60  66  80  86  84
第15號  67  60  71  62  84

In [21]:
df1.iloc[:5,:]

國文  英文  數學  物理  化學
第1號  74  55  65  55  85
第2號  89  51  59  63  62
第3號  95  78  73  92  85
第4號  64  77  78  63  95
第5號  92  55  80  72  62

In [25]:
df1.iloc[:10,:3]

國文  英文  數學
第1號   74  55  65
第2號   89  51  59
第3號   95  78  73
第4號   64  77  78
第5號   92  55  80
第6號   95  86  87
第7號   66  73  50
第8號   67  57  52
第9號   59  75  71
第10號  64  70  54

In [26]:
df1.sum(axis=0)

國文    3672
英文    3667
數學    3821
物理    3687
化學    3686
dtype: int64

In [31]:
student_sum = df1.sum(axis=1)
student_mean = df1.mean(axis=1)
df2 = pd.DataFrame(data=df1)
df2['總分'] = student_sum
df2['平均'] = student_mean
df2

國文   英文  數學  物理  化學   總分    平均
第1號    74   55  65  55  85  334  66.8
第2號    89   51  59  63  62  324  64.8
第3號    95   78  73  92  85  423  84.6
第4號    64   77  78  63  95  377  75.4
第5號    92   55  80  72  62  361  72.2
第6號    95   86  87  68  96  432  86.4
第7號    66   73  50  75  63  327  65.4
第8號    67   57  52  56  95  327  65.4
第9號    59   75  71  98  81  384  76.8
第10號   64   70  54  77  63  328  65.6
第11號   83   58  95  59  81  376  75.2
第12號   50   59  86  89  75  359  71.8
第13號   54   68  93  83  52  350  70.0
第14號   60   66  80  86  84  376  75.2
第15號   67   60  71  62  84  344  68.8
第16號   89   63  81  51  70  354  70.8
第17號   50   97  74  71  90  382  76.4
第18號   91   60  61  61  70  343  68.6
第19號   94   79  77  81  78  409  81.8
第20號   54   75  51  89  84  353  70.6
第21號   51   97  57  97  66  368  73.6
第22號   61   58  79  71  63  332  66.4
第23號   76   83  72  58  93  382  76.4
第24號   57   99  93  52  92  393  78.6
第25號   99   94  96  95  85  469  93.8
第26號   53   98  77  92  57  377  75.4
第27號   75   66  61  74  95  371  74.2
第28號   67   54  98  96  64  379  75.8
第29號   87   70  94  50  58  359  71.8
第30號   65   95  70  51  75  356  71.2
第31號   70   52  89  59  81  351  70.2
第32號   60   97  74  79  97  407  81.4
第33號   99   62  87  56  53  357  71.4
第34號   51   64  82  62  64  323  64.6
第35號   64   54  71  71  77  337  67.4
第36號   94   88  81  83  63  409  81.8
第37號   91  100  56  92  95  434  86.8
第38號   57   92  74  54  87  364  72.8
第39號   99   75  54  82  63  373  74.6
第40號   56   53  81  81  73  344  68.8
第41號   91   90  89  87  58  415  83.0
第42號   81   52  72  87  70  362  72.4
第43號   65   89  87  64  50  355  71.0
第44號   68   90  82  98  80  418  83.6
第45號   91   59  76  53  51  330  66.0
第46號  100   61  96  94  83  434  86.8
第47號   77   69  97  83  58  384  76.8
第48號   64   78  90  82  65  379  75.8
第49號   94   99  81  80  58  412  82.4
第50號   52   67  67  53  57  296  59.2